apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mri-brain-tumor-detection-ui-deployment
  name: mri-brain-tumor-detection-ui-deployment
  namespace: mri-brain-tumor-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mri-brain-tumor-detection-ui-deployment
  template:
    metadata:
      labels:
        run: mri-brain-tumor-detection-ui-deployment
    spec:
      containers:
        - name: mri-brain-tumor-detection-ui
          image: ninepiece2/mri-brain-tumor-detection:ui
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: BASE_URL
              value: "https://mri-brain-tumor-detection-internal-service:443"
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mri-brain-tumor-detection-api-deployment
  namespace: mri-brain-tumor-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mri-brain-tumor-detection-api-deployment
  template:
    metadata:
      labels:
        app: mri-brain-tumor-detection-api-deployment
    spec:
      containers:
        - name: mri-brain-tumor-detection-api
          image: ninepiece2/mri-brain-tumor-detection:api
          imagePullPolicy: Always
          ports:
            - containerPort: 443

---

apiVersion: v1
kind: Service
metadata:
  name: mri-brain-tumor-detection-service
  namespace: mri-brain-tumor-detection
spec:
  selector:
    run: mri-brain-tumor-detection-ui-deployment
  ports:
    - name: https
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30006
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: mri-brain-tumor-detection-internal-service
  namespace: mri-brain-tumor-detection
spec:
  selector:
    app: mri-brain-tumor-detection-api-deployment
  ports:
    - port: 443
      targetPort: 443
  type: ClusterIP
